{% set name = "wagtail-trash" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-trash-{{ version }}.tar.gz
  sha256: 4d85c9770175f6eccca8a18fcff81bdbf861bae6a0a736777d7ea4ce53a302da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - wheel
    - pip
  run:
    - python >=3.8
    - wagtail >=4.1

test:
  imports:
    - wagtail_trash
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Make deleted pages only temporarily deleted.
  home: https://github.com/Frojd/wagtail-trash/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
