{% set name = "wagtail-trash" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2c0f4a5da69e6bf71e1d1ef9b384a58c087d37866cf7646d1b1a35547e46f5ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - pip
    - setuptools
  run:
    - django
    - django-treebeard
    - python >={{ python_min }}
    - wagtail >=5.2
    - wagtail-modeladmin

test:
  imports:
    - wagtail_trash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Make deleted pages only temporarily deleted.
  home: https://github.com/Frojd/wagtail-trash/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
