{% set name = "wagtail-trash" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-trash-{{ version }}.tar.gz
  sha256: 913a61d2020208180d8bbb85b112fd29bd61c3cad98072cafdd77ee39e852a98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=4.1
    - wagtail-modeladmin

test:
  imports:
    - wagtail_trash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Make deleted pages only temporarily deleted.
  home: https://github.com/Frojd/wagtail-trash/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
